# Generated by Django 4.2.7 on 2023-12-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0002_remove_logindetails_id_alter_logindetails_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('omsadmin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loginapp.omsadmin')),
            ],
            bases=('loginapp.omsadmin',),
        ),
    ]
