# Generated by Django 4.2.7 on 2023-11-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OmsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('shipMethod', models.CharField(max_length=255)),
                ('processingDays', models.IntegerField()),
                ('processingDaysType', models.CharField(max_length=255)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('processingDate', models.DateField()),
                ('availableToPromiseDate', models.DateField()),
                ('cutOff', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.logindetails')),
            ],
        ),
    ]
